---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

---
title: "Iris Analysis"
author: "Rakha Hafish Setiawan"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r echo=FALSE,include=FALSE}
library(tidyverse)
library(skimr)
library(validate)
library(psych)
library(GGally)
```

```{r echo=FALSE}
iris %>%
  rename(Petal_Length = Petal.Length) %>%
  rename(Petal_Width = Petal.Width) %>%
  rename(Sepal_Width = Sepal.Width) %>%
  rename(Sepal_Length = Sepal.Length) %>%
  mutate(ID = row_number()) %>%
  select(Species, everything()) %>%
  arrange(Species)
```

```{r echo = FALSE}
iris %>%
  group_by(Species) %>%
  summarise(Count = n())
```

```{r echo=FALSE}
skim(iris)
```
```{r echo = FALSE}
describe(iris)
```

```{r}
pairs.panels(iris[1:4])
```

```{r echo =FALSE}
iris %>%
  ggplot(aes(Sepal.Width))+
  geom_histogram(stat = "count", binwidth = 5) +
  facet_wrap(~Species) +
  labs(y = "",
       x = "Sepal Width")
```
```{r echo =FALSE, results='hide', fig.keep='all'}
iris %>%
  ggplot(aes(Sepal.Length))+
  geom_histogram(stat = "count", binwidth = 5) +
  facet_wrap(~Species) +
  labs( y = "", 
        x = "Sepal Length")
```

```{r}
VAL <- validator(
  Sepal.Length > 5.84,
  Sepal.Width > 3.06,
  Petal.Length > 3.76,
  Petal.Width > 1.20
  )
```

```{r echo=FALSE}
confront(iris, VAL)
```

```{r echo=FALSE,results='hide',fig.keep='all'}
barplot(confront(iris, VAL))
```


```{r}
summary(lm(Sepal.Width~Sepal.Length, data = iris))
```






